# Generated by Django 4.1.7 on 2023-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
    ]
