# Generated by Django 4.1.7 on 2023-02-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0003_prices_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='price_id',
            new_name='price',
        ),
    ]
