# Generated by Django 4.1.7 on 2023-02-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0004_rename_price_id_services_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='price',
            new_name='amount',
        ),
    ]
