# Generated by Django 4.1.7 on 2023-02-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0005_rename_price_prices_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='price',
            new_name='amount',
        ),
    ]
