# Generated by Django 4.1.7 on 2023-02-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0006_rename_price_services_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='amount',
            new_name='price',
        ),
    ]
