# Generated by Django 4.1.7 on 2023-02-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0007_rename_amount_services_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='amount',
            new_name='price',
        ),
    ]
